#!/bin/bash
# installation script for c-tools

echo Installing c-tools to $1...

# create installation directory if it does not exist
if [ -x $1 ]; then echo -n; else mkdir $1; fi

# build
make clean
make
make clean

# move executable to installation directory
cp c-tools $1

# add aliases to bash startup file
INSTALL_ALIASES="alias line2multi 'c-tools line2multi'"

if [ -x ~/.bashrc ]; then
    STARTUP_FILE=~/.bashrc;
elif [ -x ~/.bash_profile ]; then
    STARTUP_FILE=~/.bash_profile;
fi

echo -ne $INSTALL_ALIASES >> $STARTUP_FILE

# finished!
echo Done